dataset:
  simulated:
      n_samples, n_features:
        - [1000, 100]
        - [5000, 10]

solver:
  svm:
    kernel: ["linear", "poly"]
  torch-logreg:
    lr: [0.01]
    batch_size: [64, 256]

n_repetitions: 3
timeout: 30
seed: 0
n-jobs: 1
